### ISSUE TITLE
rdoc fails on version 1.0.2

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [sparklemotion/http-cookie#4]
Installing ri documentation for http-cookie-1.0.2...
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /Users/republicofapps/.rvm/rubies/ruby-1.9.3-p484/bin/ruby -c lib/http/cookie.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

```
(NoMethodError) undefined method `last' for nil:NilClass
```

ERROR:  While generating documentation for http-cookie-1.0.2
... MESSAGE:   undefined method `last' for nil:NilClass
... RDOC args: --ri --op /Users/republicofapps/.rvm/gems/ruby-1.9.3-p484@herokucedar/doc/http-cookie-1.0.2/ri lib README.md LICENSE.txt --title http-cookie-1.0.2 Documentation --quiet

**Comment by flavorjones** [comment]
I can't reproduce this now, apologies.
