### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by jesseclark** [sparklemotion/http-cookie#48]
Hello 👋🏼 

Are there any plans to do a new release soon?

I am using the `http` gem which uses `http-cookie` and in the industry I am in we get a lot of non-rfc3986 compliant URIs as redirects and releasing this [change](https://github.com/sparklemotion/http-cookie/commit/8930674adf5b80c93e889bc2350d0a65f251fb5d) would be a big help. 🙇🏼

**Comment by flavorjones** [comment]
@knu I'd be happy to cut a release if you add me to the gem on rubygems.org. Let me know how I can help!

**Comment by knu** [comment]
I've just pushed v1.0.6, and noticed I forgot to update the CHANGELOG.

**Comment by knu** [comment]
I've updated CHANGELOG.md anyway (after the v1.0.6 tag) and added @flavorjones as a gem owner.

**Comment by flavorjones** [comment]
@knu Thank you!

**Comment by jesseclark** [comment]
@knu Thanks a lot!
