### ISSUE TITLE
1.0.7 is not available at rubygems.org

### ISSUE THREAD

**Issue by chulkilee** [sparklemotion/http-cookie#51]
https://rubygems.org/gems/http-cookie/versions

**Comment by flavorjones** [comment]
@knu When you added me to the gem on rubygems.org, I did not accept fast enough. As a result, when I ran `gem push` the upload failed.

Can you please add me again? Thank you.

**Comment by knu** [comment]
@flavorjones I removed you and then readded.  I hope you will receive a new invitation.

**Comment by flavorjones** [comment]
@knu Thank you! All good now.

@chulkilee I just pushed 1.0.7. Thank you again!
